"""add_master_and_operational_timestamps

Revision ID: 17a1289fc8b1
Revises: a97f9af66af4
Create Date: 2026-05-19 11:31:22.757104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a1289fc8b1'
down_revision: Union[str, Sequence[str], None] = 'a97f9af66af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_violations', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True), schema='verity')
    op.add_column('personnel', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='verity')
    op.add_column('personnel', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='verity')
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='verity')
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='verity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at', schema='verity')
    op.drop_column('projects', 'created_at', schema='verity')
    op.drop_column('personnel', 'updated_at', schema='verity')
    op.drop_column('personnel', 'created_at', schema='verity')
    op.drop_column('compliance_violations', 'resolved_at', schema='verity')
    # ### end Alembic commands ###
