"""Add phase 7 models

Revision ID: 30daf3151e4c
Revises: 17a1289fc8b1
Create Date: 2026-05-22 17:20:40.470373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30daf3151e4c'
down_revision: Union[str, Sequence[str], None] = '17a1289fc8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('asset_category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='verity'
    )
    op.create_index(op.f('ix_verity_procurement_po_number'), 'procurement', ['po_number'], unique=True, schema='verity')
    op.create_table('inventory',
    sa.Column('asset_tag', sa.String(length=100), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('assigned_employee_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('IN_USE', 'RETIRED', 'LOST', name='assetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['verity.personnel.employee_id'], ),
    sa.ForeignKeyConstraint(['po_number'], ['verity.procurement.po_number'], ),
    sa.PrimaryKeyConstraint('asset_tag'),
    schema='verity'
    )
    op.create_table('asset_violations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('violation_type', sa.Enum('GHOST_ASSET', 'WASTED_SPEND', name='assetviolationtype'), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='assetviolationstatus'), nullable=False),
    sa.Column('resolution_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_tag'], ['verity.inventory.asset_tag'], ),
    sa.ForeignKeyConstraint(['po_number'], ['verity.procurement.po_number'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='verity'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_violations', schema='verity')
    op.drop_table('inventory', schema='verity')
    op.drop_index(op.f('ix_verity_procurement_po_number'), table_name='procurement', schema='verity')
    op.drop_table('procurement', schema='verity')
    # ### end Alembic commands ###
