"""Add department and export_control_status to projects

Revision ID: 5122b545ca31
Revises: 9684b4f85ca2
Create Date: 2026-05-15 16:03:25.053383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5122b545ca31'
down_revision: Union[str, Sequence[str], None] = '9684b4f85ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('department', sa.String(length=255), nullable=True), schema='verity')
    op.add_column('projects', sa.Column('export_control_status', sa.String(length=255), nullable=False), schema='verity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'export_control_status', schema='verity')
    op.drop_column('projects', 'department', schema='verity')
    # ### end Alembic commands ###
