"""add_itar_tables

Revision ID: 8812cffddd3f
Revises: f1597f371eab
Create Date: 2026-05-13 16:12:55.108875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8812cffddd3f'
down_revision: Union[str, Sequence[str], None] = 'f1597f371eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('citizenship_status', sa.Enum('US_CITIZEN', 'PERMANENT_RESIDENT', 'FOREIGN_NATIONAL', 'UNKNOWN', name='citizenshipstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='verity'
    )
    op.create_index(op.f('ix_verity_personnel_employee_id'), 'personnel', ['employee_id'], unique=True, schema='verity')
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sensitivity', sa.Enum('ITAR_RESTRICTED', 'EAR99', 'UNCLASSIFIED', name='projectsensitivity'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='verity'
    )
    op.create_index(op.f('ix_verity_projects_project_id'), 'projects', ['project_id'], unique=True, schema='verity')
    op.create_table('compliance_violations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['verity.personnel.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['verity.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='verity'
    )
    op.create_table('project_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['verity.personnel.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['verity.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='verity'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_assignments', schema='verity')
    op.drop_table('compliance_violations', schema='verity')
    op.drop_index(op.f('ix_verity_projects_project_id'), table_name='projects', schema='verity')
    op.drop_table('projects', schema='verity')
    op.drop_index(op.f('ix_verity_personnel_employee_id'), table_name='personnel', schema='verity')
    op.drop_table('personnel', schema='verity')
    # ### end Alembic commands ###
