"""Move personnel and project models to data_hub

Revision ID: 8da21312db49
Revises: 8812cffddd3f
Create Date: 2026-05-15 14:42:19.174053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da21312db49'
down_revision: Union[str, Sequence[str], None] = '8812cffddd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_violations', sa.Column('resolution_reason', sa.String(), nullable=True), schema='verity')
    op.add_column('personnel', sa.Column('termination_date', sa.Date(), nullable=True), schema='verity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personnel', 'termination_date', schema='verity')
    op.drop_column('compliance_violations', 'resolution_reason', schema='verity')
    # ### end Alembic commands ###
