"""Add intake_records table

Revision ID: f1597f371eab
Revises: fa38a300acde
Create Date: 2026-05-08 15:26:44.256056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1597f371eab'
down_revision: Union[str, Sequence[str], None] = 'fa38a300acde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='verity'
    )
    op.create_index(op.f('ix_verity_intake_records_job_id'), 'intake_records', ['job_id'], unique=False, schema='verity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verity_intake_records_job_id'), table_name='intake_records', schema='verity')
    op.drop_table('intake_records', schema='verity')
    # ### end Alembic commands ###
