"""add file metadata table

Revision ID: fa38a300acde
Revises: 6c4d75d678cb
Create Date: 2026-04-28 15:09:43.824190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa38a300acde'
down_revision: Union[str, Sequence[str], None] = '6c4d75d678cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS verity')
    op.create_table('file_metadata',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('file_id'),
    schema='verity'
    )
    op.create_index(op.f('ix_verity_file_metadata_job_id'), 'file_metadata', ['job_id'], unique=False, schema='verity')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='verity'
    )
    op.create_index(op.f('ix_verity_users_email'), 'users', ['email'], unique=True, schema='verity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verity_users_email'), table_name='users', schema='verity')
    op.drop_table('users', schema='verity')
    op.drop_index(op.f('ix_verity_file_metadata_job_id'), table_name='file_metadata', schema='verity')
    op.drop_table('file_metadata', schema='verity')
    # ### end Alembic commands ###
